version: "3"

services:
  map-demo-prod-service:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: map-demo-prod
    container_name: map-demo-prod-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/map-demo-prod
    command: yarn start:prod
    env_file: ./.env
