version: "3"

services:
  map-demo-dev-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: map-demo-dev
    container_name: map-demo-dev-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/map-demo-dev
      - /usr/src/map-demo-dev/node_modules
    command: yarn run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ./.env.example
